# Product-owned UI adapter. Runs in Windows PowerShell STA for built-in UI Automation.
# Payload travels through stdin, never through a command line or a script generated by a model.
param([switch]$CheckOnly)
$ErrorActionPreference = 'Stop'
try {
    Add-Type -AssemblyName UIAutomationClient, UIAutomationTypes
    Add-Type -ReferencedAssemblies UIAutomationClient, UIAutomationTypes, WindowsBase -TypeDefinition @'
using System;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Windows.Automation;

public static class RawmNotepad {
    [DllImport("user32.dll")] static extern IntPtr GetForegroundWindow();
    [DllImport("user32.dll")] static extern bool SetForegroundWindow(IntPtr window);
    [DllImport("user32.dll")] static extern IntPtr GetAncestor(IntPtr window, uint flag);
    [DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr window, out uint pid);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] static extern int GetClassName(IntPtr window, StringBuilder name, int length);
    [DllImport("user32.dll", CharSet=CharSet.Unicode)] static extern IntPtr SendMessageTimeout(IntPtr window, uint message, IntPtr w, string text, uint flags, uint timeout, out IntPtr result);

    static string ReadText(AutomationElement editor) {
        object pattern;
        if (editor.TryGetCurrentPattern(TextPattern.Pattern, out pattern)) {
            return ((TextPattern)pattern).DocumentRange.GetText(16002).Replace("\r\n", "\n").Replace("\r", "\n");
        }
        if (editor.TryGetCurrentPattern(ValuePattern.Pattern, out pattern)) {
            return ((ValuePattern)pattern).Current.Value.Replace("\r\n", "\n").Replace("\r", "\n");
        }
        throw new InvalidOperationException("Notepad did not expose readable editor text. Nothing was typed.");
    }
    static bool IsTrustedNotepad(int pid) {
        using (var process = Process.GetProcessById(pid)) {
            if (!String.Equals(process.ProcessName, "notepad", StringComparison.OrdinalIgnoreCase)) return false;
            string path = process.MainModule.FileName;
            string classic = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "notepad.exe");
            string packaged = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "WindowsApps", "Microsoft.WindowsNotepad_");
            return String.Equals(path, classic, StringComparison.OrdinalIgnoreCase) ||
                (path.StartsWith(packaged, StringComparison.OrdinalIgnoreCase) && String.Equals(Path.GetFileName(path), "Notepad.exe", StringComparison.OrdinalIgnoreCase));
        }
    }
    static AutomationElement FindWindow(string marker) {
        var windows = AutomationElement.RootElement.FindAll(TreeScope.Children,
            new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Window));
        AutomationElement found = null;
        foreach (AutomationElement window in windows) {
            if (window.Current.Name.IndexOf(marker, StringComparison.Ordinal) < 0) continue;
            if (!IsTrustedNotepad(window.Current.ProcessId)) continue;
            if (found != null) throw new InvalidOperationException("Multiple matching Notepad windows. Nothing was typed.");
            found = window;
        }
        return found;
    }
    static AutomationElement FindEditor(AutomationElement window) {
        var candidates = window.FindAll(TreeScope.Descendants, new OrCondition(
            new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Document),
            new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Edit)));
        AutomationElement found = null;
        foreach (AutomationElement item in candidates) {
            if (item.Current.IsOffscreen || !item.Current.IsEnabled || item.Current.NativeWindowHandle == 0) continue;
            var name = new StringBuilder(128);
            GetClassName(new IntPtr(item.Current.NativeWindowHandle), name, name.Capacity);
            if (name.ToString() != "Edit" && name.ToString() != "RichEditD2DPT" && name.ToString() != "RICHEDIT50W") continue;
            if (found != null) throw new InvalidOperationException("Multiple editable surfaces. Nothing was typed.");
            found = item;
        }
        return found;
    }
    static void VerifyTarget(AutomationElement window, AutomationElement editor, string marker) {
        var top = new IntPtr(window.Current.NativeWindowHandle);
        var edit = new IntPtr(editor.Current.NativeWindowHandle);
        uint editPid;
        GetWindowThreadProcessId(edit, out editPid);
        if (window.Current.Name.IndexOf(marker, StringComparison.Ordinal) < 0 ||
            !IsTrustedNotepad(window.Current.ProcessId) || editPid != window.Current.ProcessId ||
            GetAncestor(edit, 2) != top || GetForegroundWindow() != top ||
            !editor.Current.HasKeyboardFocus || !editor.Current.IsEnabled || editor.Current.IsOffscreen) {
            throw new InvalidOperationException("Notepad target or focus changed. Stopped without further input.");
        }
    }
    public static string Write(string drafts, string text) {
        string marker = "RAWM-" + Guid.NewGuid().ToString("N");
        string path = Path.Combine(drafts, marker + ".txt");
        using (File.Open(path, FileMode.CreateNew, FileAccess.Write, FileShare.Read)) { }
        var start = new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "notepad.exe"));
        start.UseShellExecute = false;
        // Do not let the long-lived editor inherit the helper's output pipes.
        start.RedirectStandardInput = true;
        start.RedirectStandardOutput = true;
        start.RedirectStandardError = true;
        start.Arguments = "\"" + path + "\"";
        using (var launched = Process.Start(start)) { launched.StandardInput.Close(); }
        var deadline = DateTime.UtcNow.AddSeconds(20);
        AutomationElement window = null, editor = null;
        while (DateTime.UtcNow < deadline) {
            window = FindWindow(marker);
            if (window != null) editor = FindEditor(window);
            if (editor != null) break;
            Thread.Sleep(150);
        }
        if (window == null || editor == null) throw new InvalidOperationException("Notepad opened, but a unique editable draft was not found. Nothing was typed.");
        SetForegroundWindow(new IntPtr(window.Current.NativeWindowHandle));
        editor.SetFocus();
        Thread.Sleep(150);
        VerifyTarget(window, editor, marker);
        if (ReadText(editor).Length != 0) throw new InvalidOperationException("Draft is no longer empty. Nothing was typed.");
        if (text.Length > 0) {
            VerifyTarget(window, editor, marker);
            IntPtr result;
            // Targeted, undoable literal insertion. No global keystrokes, clipboard, or save shortcut.
            if (SendMessageTimeout(new IntPtr(editor.Current.NativeWindowHandle), 0x00C2, new IntPtr(1), text, 0x0002, 2000, out result) == IntPtr.Zero)
                throw new InvalidOperationException("Text entry timed out; inspect the draft before retrying.");
        }
        string expected = text.Replace("\r\n", "\n").Replace("\r", "\n");
        deadline = DateTime.UtcNow.AddSeconds(3);
        do {
            VerifyTarget(window, editor, marker);
            if (ReadText(editor) == expected) {
                if (new FileInfo(path).Length != 0) throw new InvalidOperationException("The scratch file changed on disk. Inspect it before retrying.");
                return "Opened Notepad and verified " + text.Length + " characters in draft " + marker + ". RAWM did not save the entered text.";
            }
            Thread.Sleep(100);
        } while (DateTime.UtcNow < deadline);
        throw new InvalidOperationException("Notepad text could not be verified. Inspect the draft before retrying; RAWM will not repeat the input.");
    }
}
'@
    if ($CheckOnly) { @{status='compiled';message='Windows UI Automation adapter compiled.'} | ConvertTo-Json -Compress; return }
    $encoded = [Console]::ReadLine()
    $request = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($encoded)) | ConvertFrom-Json
    if ($request.text -isnot [string] -or $request.text.Length -gt 16000 -or $request.text -match '[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]') { throw 'Invalid text payload.' }
    $message = [RawmNotepad]::Write([string]$request.drafts, [string]$request.text)
    @{status='verified'; message=$message} | ConvertTo-Json -Compress
} catch {
    # All adapter messages are fixed application diagnostics, not input text or UI contents.
    @{status='uncertain'; message=$_.Exception.Message} | ConvertTo-Json -Compress
}
